### ISSUE TITLE
C&P from plain text viewer is missing line feeds

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#410] opened 2022-01-05 10:38 UTC
If you try to copy and paste the contents of the plain text viewer line feeds are missing from the pasted data.

**Comment by OliverDudgeon** [comment] 2022-05-29 20:13
I can't reproduce this. When I copy a section into a plaintext editor, new lines are there. In fact an extra new line per line is pasted....

**Comment by OliverDudgeon** [comment] 2022-08-26 17:34
Fixed with new viewer

**Closed by OliverDudgeon** 2022-08-26 17:34 UTC
Labels: bug, viewer
